sudo: required

services:
  - docker

script:
  - docker build -t cetres/android-ionic .
  - docker run cetres/android-ionic /bin/sh -c "ionic -v && ionic start test && cd test && ionic platform add android && ionic build android"
